#FROM maven:3.8.5-openjdk-17 AS build
#COPY . .
#RUN mvn clean package -DskipTests
#
#FROM openjdk:17.0.1-jdk-slim
#COPY --from=build /target/hngTask1-0.0.1-SNAPSHOT.jar hngTask1.jar
#EXPOSE 8080
#ENTRYPOINT ["java","-jar","demo.jar"]
#
#
#
## Use an official OpenJDK runtime as a base image
#FROM openjdk:11-jre-slim
#
## Set the working directory inside the container
#WORKDIR /app

## Copy the Spring Boot application JAR file into the container
#COPY target/hngTask1.jar app.jar
#
## Expose the port your Spring Boot app is listening on (default is 8080)
#EXPOSE 8080
#
## Command to run the application when the container starts
#CMD ["java", "-jar", "app.jar"]

