#FROM jelastic/maven:3.8.6-openjdk-20.ea-b24 AS build
#COPY . .
#RUN mvn clean package -DskipTests
#
#FROM openjdk:20-jdk-slim
#COPY --from=build /target/hngTask1-0.0.1-SNAPSHOT.jar hngTask1.jar
#EXPOSE 8080
#ENTRYPOINT ["java","-jar","hngTask1.jar"]

# Stage 1: Build the application
FROM maven:3.8.6-openjdk-20.ea-b24 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Stage 2: Create the final image
FROM openjdk:20-jdk-slim
WORKDIR /app
COPY --from=build /app/target/hngTask1-0.0.1-SNAPSHOT.jar hngTask1.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "hngTask1.jar"]

